name: PR template

on:
  push:

jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Run unit tests
        run: |
          npm ci
          npm run test
